document.documentElement.classList.add('js');
document.addEventListener('DOMContentLoaded',()=>{
 const nav=document.getElementById('mainNav'),toggle=document.getElementById('menuToggle'),header=document.getElementById('siteHeader');
 const closeMenu=()=>{nav?.classList.remove('open');toggle?.classList.remove('open');toggle?.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')};
 toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});
 nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu)); document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()}); document.addEventListener('click',e=>{if(window.innerWidth<900&&nav?.classList.contains('open')&&!nav.contains(e.target)&&!toggle?.contains(e.target))closeMenu()});
 const onScroll=()=>header?.classList.toggle('scrolled',window.scrollY>18); onScroll(); window.addEventListener('scroll',onScroll,{passive:true});
 const year=document.getElementById('year'); if(year) year.textContent=new Date().getFullYear();
 const setLanguage=(lang)=>{const l=lang==='hi'?'hi':'en';document.documentElement.lang=l;document.querySelectorAll('[data-en][data-hi]').forEach(el=>{if(el.matches('input,textarea'))el.placeholder=el.dataset[l];else el.textContent=el.dataset[l]});document.querySelectorAll('[data-lang]').forEach(el=>el.classList.toggle('active',el.dataset.lang===l));localStorage.setItem('rjLanguage',l)};
 setLanguage(localStorage.getItem('rjLanguage')||'en'); document.querySelectorAll('.lang-btn').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));
 document.querySelectorAll('a[href*="solar/"]').forEach(a=>a.addEventListener('click',()=>localStorage.setItem('rjLanguage',document.documentElement.lang||'en')));
 const reveal=[...document.querySelectorAll('[data-reveal],.reveal')]; if('IntersectionObserver' in window){const io=new IntersectionObserver((entries,obs)=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');obs.unobserve(e.target)}}),{threshold:.10,rootMargin:'0px 0px -45px'});reveal.forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i%6,5)*55}ms`;io.observe(el)})}else reveal.forEach(el=>el.classList.add('is-visible'));
 const map=document.getElementById('energyMap'); if(map){const title=document.getElementById('energyStoryTitle'),text=document.getElementById('energyStoryText');const copy={property:['Your property is where every good solar decision begins.','Roof direction, usable area, shade and real electricity use become the starting coordinates.'],plan:['Good planning makes the system feel simple.','We connect your energy need with practical system sizing, product fit and site conditions.'],solar:['The system works as one connected design.','Panels, inverter, structure and compatibility have to work together.'],install:['The plan becomes real on site.','Installation is where layout, safety, connection and commissioning come together.'],result:['The goal is a clear working energy setup.','A practical system should make sense for the property and the way it is used.']};map.querySelectorAll('.energy-node').forEach(n=>n.addEventListener('click',()=>{map.querySelectorAll('.energy-node').forEach(x=>x.classList.remove('active'));n.classList.add('active');const c=copy[n.dataset.node];if(c){title.textContent=c[0];text.textContent=c[1]}}))}
 if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const hero=document.querySelector('.hero');addEventListener('pointermove',e=>{if(!hero||innerWidth<900)return;const x=(e.clientX/innerWidth-.5),y=(e.clientY/innerHeight-.5);hero.style.setProperty('--mx',`${x*14}px`);hero.style.setProperty('--my',`${y*10}px`)},{passive:true})}
 const form=document.getElementById('quoteForm'),note=document.getElementById('formNote');form?.addEventListener('submit',e=>{e.preventDefault();if(note){const hi=document.documentElement.lang==='hi';note.textContent=hi?'धन्यवाद। आपकी पूछताछ तैयार है। इस डेमो फॉर्म को ईमेल/CRM सेवा से जोड़कर लाइव सबमिशन किया जा सकता है।':'Thank you. Your enquiry is ready; connect this form to your email/CRM provider for live submissions.';note.classList.add('success')}});
});
